<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-04T00:01:27 IST" name="Suite" finished-at="2022-11-04T00:02:12 IST" duration-ms="44226">
    <groups>
    </groups>
    <test started-at="2022-11-04T00:01:27 IST" name="Test" finished-at="2022-11-04T00:02:12 IST" duration-ms="44226">
      <class name="TestCases.VerifySignup">
        <test-method is-config="true" signature="LaunchURL()[pri:0, instance:TestCases.VerifySignup@123ef382]" started-at="2022-11-04T00:01:28 IST" name="LaunchURL" finished-at="2022-11-04T00:01:37 IST" duration-ms="9932" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchURL -->
        <test-method signature="signup()[pri:0, instance:TestCases.VerifySignup@123ef382]" started-at="2022-11-04T00:01:37 IST" name="signup" finished-at="2022-11-04T00:02:08 IST" duration-ms="30457" status="FAIL">
          <exception class="java.lang.UnsupportedOperationException">
            <message>
              <![CDATA[You may not select a disabled option]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.UnsupportedOperationException: You may not select a disabled option
at org.openqa.selenium.support.ui.Select.assertOptionIsEnabled(Select.java:326)
at org.openqa.selenium.support.ui.Select.setSelected(Select.java:318)
at org.openqa.selenium.support.ui.Select.setSelectedByIndex(Select.java:301)
at org.openqa.selenium.support.ui.Select.selectByIndex(Select.java:180)
at Resources.CommonUtilities.handleStaticDropdown(CommonUtilities.java:22)
at TestCases.VerifySignup.signup(VerifySignup.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.UnsupportedOperationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signup -->
      </class> <!-- TestCases.VerifySignup -->
      <class name="TestCases.VerifyLogin">
        <test-method is-config="true" signature="LaunchURL()[pri:0, instance:TestCases.VerifyLogin@52bf72b5]" started-at="2022-11-04T00:02:08 IST" name="LaunchURL" finished-at="2022-11-04T00:02:11 IST" duration-ms="3524" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchURL -->
        <test-method signature="login()[pri:0, instance:TestCases.VerifyLogin@52bf72b5]" started-at="2022-11-04T00:02:11 IST" name="login" finished-at="2022-11-04T00:02:12 IST" duration-ms="225" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Input must be set]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Input must be set
at org.openqa.selenium.internal.Require.nonNull(Require.java:59)
at org.openqa.selenium.support.ui.FluentWait.<init>(FluentWait.java:97)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:77)
at org.openqa.selenium.support.ui.WebDriverWait.<init>(WebDriverWait.java:46)
at Resources.CommonUtilities.handleExplicitWait(CommonUtilities.java:40)
at TestCases.VerifyLogin.login(VerifyLogin.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- TestCases.VerifyLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
